### ISSUE TITLE
crash with instruction variant

### ISSUE THREAD

**Issue by sebseb7** [michaelkamprath/bespokeasm#11]
bespokeasm-script.py compile -c testcase_isa.yaml testcase.asm -p

testcase.asm
```
.org 0x0000
	add c,b ; fails
	add2 c,b ; doesn't fail
	add c,a ; doesn't fail
	add b,c ; doesn't fail
	add b,b ; fails
```

testcase_isa.yaml
```
description: SEB ISA
general:
  min_version: 0.1.4
  endian: big
  address_size: 16
  registers:
    - a
    - b
    - c
    - d
  identifier:
    name: seb-isa
    version: "1.0.0"
    extension: seb1
operand_sets:
  integer:
    operand_values:
      int8:
        type: numeric
        argument:
          size: 8
          byte_align: true
  register:
    operand_values:
      register_a:
        type: register
        register: a
        bytecode:
          value: 1
          size: 4
          position: suffix
      register_b:
        type: register
        register: b
        bytecode:
          value: 2
          size: 4
          position: suffix
      register_c:
        type: register
        register: c
        bytecode:
          value: 3
          size: 4
          position: suffix
      register_d:
        type: register
        register: d
        bytecode:
          value: 4
          size: 4
          position: suffix
instructions:
  add:
    byte_code:
      value: 1
      size: 8
    operands:
      count: 2
      operand_sets:
        list:
          - register
          - integer
    variants:
      - var1:
        byte_code:
          value: 2
          size: 8
        operands:
          count: 2
          operand_sets:
            list:
              - register
              - register
  add2:
    byte_code:
      value: 2
      size: 8
    operands:
      count: 2
      operand_sets:
        list:
          - register
          - register
```

error:
```
$ bespokeasm-script.py compile -c testcase_isa.yaml testcase.asm -p
Traceback (most recent call last):
  File "C:\Python39\Scripts\bespokeasm-script.py", line 33, in <module>
    sys.exit(load_entry_point('bespokeasm==0.2.1', 'console_scripts', 'bespokeasm')())
  File "C:\python39\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\python39\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\python39\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\python39\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\python39\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\python39\lib\site-packages\bespokeasm\__main__.py", line 83, in compile
    asm.assemble_bytecode()
  File "C:\python39\lib\site-packages\bespokeasm\assembler\__init__.py", line 71, in assemble_bytecode
    line_obs: list[LineObject] = asm_file.load_line_objects(self._model, include_dirs, self._verbose)
  File "C:\python39\lib\site-packages\bespokeasm\assembler\assembly_file.py", line 75, in load_line_objects
    lobj_list = LineOjectFactory.parse_line(line_id, line_str, isa_model)
  File "C:\python39\lib\site-packages\bespokeasm\assembler\line_object\factory.py", line 66, in parse_line
    line_obj = InstructionLine.factory(line_id, instruction_str, comment_str, model)
  File "C:\python39\lib\site-packages\bespokeasm\assembler\line_object\instruction_line.py", line 22, in factory
    return InstructionLine(line_id, command_str, argument_str, isa_model, line_str, comment)
  File "C:\python39\lib\site-packages\bespokeasm\assembler\line_object\instruction_line.py", line 37, in __init__
    self._assembled_instruction = self._isa_model.parse_instruction(line_id, instruction)
  File "C:\python39\lib\site-packages\bespokeasm\assembler\model\__init__.py", line 176, in parse_instruction
    return instr_obj.generate_bytecode_parts(line_id, mnemonic, operands, self.endian, self.registers)
  File "C:\python39\lib\site-packages\bespokeasm\assembler\model\instruction.py", line 209, in generate_bytecode_parts
    assembled_instruction = variant.generate_bytecode_parts(
  File "C:\python39\lib\site-packages\bespokeasm\assembler\model\instruction.py", line 134, in generate_bytecode_parts
    matched_operands = self._operand_parser.find_matching_operands(line_id, operand_list, register_labels)
  File "C:\python39\lib\site-packages\bespokeasm\assembler\model\operand_parser.py", line 239, in find_matching_operands
    self._operand_sets_model.find_operands_from_operand_sets(line_id, operands, register_labels)
  File "C:\python39\lib\site-packages\bespokeasm\assembler\model\operand_parser.py", line 73, in find_operands_from_operand_sets
    operand = self._operand_sets[i].parse_operand(line_id, operands[i], register_labels)
  File "C:\python39\lib\site-packages\bespokeasm\assembler\model\operand_set.py", line 48, in parse_operand
    op: ParsedOperand = operand.parse_operand(line_id, operand_str, register_labels)
  File "C:\python39\lib\site-packages\bespokeasm\assembler\model\operand\types\numeric_expression.py", line 32, in parse_operand
    arg_part = ExpressionByteCodePart(operand, self.argument_size, self.argument_byte_align, self.argument_endian, line_id)
  File "C:\python39\lib\site-packages\bespokeasm\assembler\byte_code\parts.py", line 71, in __init__
    self._parsed_expression = parse_expression(self.line_id, self._expression)
  File "C:\python39\lib\site-packages\bespokeasm\expression\__init__.py", line 100, in parse_expression
    tokens = _lexical_analysis(line_id, expression)
  File "C:\python39\lib\site-packages\bespokeasm\expression\__init__.py", line 126, in _lexical_analysis
    token = ExpressionNode(TokenType.T_NUM, value=parse_numeric_string(part))
  File "C:\python39\lib\site-packages\bespokeasm\utilities.py", line 14, in parse_numeric_string
    return int(numeric_str[1:], 2)
ValueError: invalid literal for int() with base 2: ''
```

**Comment by michaelkamprath** [comment]
The failure is appropriate, the error message is unhelpful and misleading. Basically, you configured the `add` instruction to take an integer (`numeric`) as the second argument and you passed the letter `b` to it.Since `b` is a register, it doesn't get interpreted as a label or constant. And a register cannot be passed where an numeric value is expected.  What adds to the confusion is that the letter `b` is also used to prefix numeric values expressed in binary, so the code is trying to make that happen, which it shouldn't because there are no `0`'s or `1`'s following it. I'll get the error message fixed.

**Comment by sebseb7** [comment]
how to get around this?

rename the b register?

**Comment by sebseb7** [comment]
seems reordering the variants does work. having the register/register variant before the register/integer variant

**Comment by sebseb7** [comment]
seems reordering the variants does work. having the register/register variant before the register/integer variant

**Comment by michaelkamprath** [comment]
OK, just pushed a fix. You should have needed to reorder the variant. Try the updated code with your original configuration. It should now work.

**Comment by michaelkamprath** [comment]
Crap ... I introduced a bug with this fix ... hold on ...

**Comment by michaelkamprath** [comment]
@sebseb7  OK, the introduced bug is fixed now. Sorry about that. You can now use the code as your originally intended.

**Comment by sebseb7** [comment]
fix confirmed
